#include<stdio.h>
int main()
{
    int d1,d2,d3,t=0,x;
    scanf("%d%d%d",&d1,&d2,&d3);
    if(d1>d2)
    {
        t=t+d2;
        if(d1+d2<=d3)
        {
            t=t+d1+d2+d1;
        }
        else
        {
            t=t+d3;
            if(d2+d3<d1)
            {
                t=t+d2+d3;
            }
            else
            {
                t=t+d1;
            }
        }
    }
    else
       {
        t=t+d1;
        if(d1+d2<=d3)
        {
            t=t+d1+d2+d2;
        }
        else
        {
            t=t+d3;
            if(d1+d3<d2)
            {
                t=t+d1+d3;
            }
            else
            {
                t=t+d2;
            }
        }
    }
    printf("%d",t);
    return 0;
}
